[package]
name = "redditbg"
version = "4.0.0"
authors = ["PurpleMyst <PurpleMyst@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bytes = "0.5.4"
directories = { version = "1.0.1", package = "directories-next" }
exponential-backoff = "0.2.2"
futures = "0.3.4"
futures-retry = "0.5.0"
image = "0.23.4"
lazy_static = "1.4.0"
noisy_float = "0.1.12"
reqwest = { version = "0.10.4", features = ["json", "stream"] }
serde_json = "1.0.52"
sha2 = "0.8.2"
slog = "2.5.2"
slog-async = "2.5.0"
slog-json = "2.3.0"
slog-term = "2.6.0"
systray = "0.4.0"
tempfile = "3.1.0"
tokio = { version = "0.2.20", features = ["macros", "time", "fs", "io-util", "blocking"] }
slog-bunyan = "2.2.0"
file-rotator = "0.2.1"
eyre = "0.6.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.8"
winrt-notification = "0.2.2"
