[package]
name = "redditbg"
version = "2.2.0"
authors = ["PurpleMyst <PurpleMyst@users.noreply.github.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"
bytes = "0.5.4"
directories = { version = "1.0.1", package = "directories-next" }
exponential-backoff = "0.2.2"
futures = "0.3.4"
futures-retry = "0.5.0"
image = "0.23.4"
lazy_static = "1.4.0"
log = "0.4.8"
noisy_float = "0.1.12"
reqwest = { version = "0.10.4", features = ["json", "stream"] }
serde_json = "1.0.52"
sha2 = "0.8.2"
simplelog = "0.7.6"
systray = "0.4.0"
tempfile = "3.1.0"
tokio = { version = "0.2.20", features = ["macros", "time", "fs", "io-util", "blocking"] }

[target.'cfg(windows)'.dependencies]
winapi = "0.3.8"
