[package]
name = "redditbg"
version = "4.1.0"
authors = ["PurpleMyst <PurpleMyst@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bytes = "1.0.1"
directories = { version = "2.0.0", package = "directories-next" }
exponential-backoff = "1.0.0"
futures = "0.3.12"
futures-retry = "0.6.0"
image = "0.23.12"
lazy_static = "1.4.0"
noisy_float = "0.1.13"
reqwest = { version = "0.11.0", features = ["json", "stream"] }
serde_json = "1.0.61"
sha2 = "0.9.2"
slog = "2.7.0"
slog-async = "2.6.0"
slog-json = "2.3.0"
slog-term = "2.6.0"
systray = "0.4.0"
tempfile = "3.2.0"
tokio = { version = "1.1.0", features = ["macros", "time", "fs", "io-util", "rt", "rt-multi-thread"] }
tokio-stream = { version = "0.1.2", features = ["fs"] }
slog-bunyan = "2.3.0"
file-rotator = "0.4.1"
eyre = "0.6.5"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"
winrt-notification = "0.2.2"
