[package]
name = "redditbg"
version = "1.2.0"
authors = ["PurpleMyst <PurpleMyst@users.noreply.github.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.28"

image = "0.23.4"

noisy_float = "0.1.12"

log = "0.4.8"
simplelog = "0.7.6"

futures = "0.3.4"
futures-retry = "0.5.0"
tokio = { version = "0.2.20", features = ["macros", "time"] }

bytes = "0.5.4"
reqwest = { version = "0.10.4", features = ["json"] }
serde_json = "1.0.52"

exponential-backoff = "0.2.2"
systray = "0.4.0"
directories = { version = "1.0.1", package = "directories-next" }
lazy_static = "1.4.0"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.8"
